site_name: MKDOCS 2
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.indexes

repo_url: https://github.com/AzureLearn1/mkdocs1
repo_name: mkdocs1

plugins:
  - search
